spring:
  application:
    name: rental-assistant
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rental_assistant}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

telegram:
  token: ${TELEGRAM_BOT_TOKEN}