CREATE TABLE raw_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender VARCHAR(255) NOT NULL,
    message_timestamp TIMESTAMP NOT NULL,
    message_text TEXT NOT NULL,
    message_hash VARCHAR(64) NOT NULL UNIQUE,
    imported_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_raw_messages_message_timestamp
    ON raw_messages (message_timestamp);
